### ISSUE TITLE
Activating other virtualenvs

### ISSUE THREAD

**Issue by ryankask** [porterjamesj/virtualenvwrapper.el#24]
Hi there! Thanks for this great project. I've recently started using it and have a question.

I'm a contractor and for most of my projects I use virtualenvwrapper and this mode works really well.

Some projects, however, use vanilla virtualenv and one has a `.venv` dir in each project directory alongside `.git`. (there are many projects)

I'd like to somehow integrate projectile's `projectile-project-root` function and use virtualenvwrapper.el to activate the virtualenv located at `project-root/.venv`. Do you have any recommendations on how to do this?

One idea would be to append paths to `venv-location` in a python-mode-hook and then use `venv-workon`.

I noticed in the Pyvenv project (https://github.com/jorgenschaefer/pyvenv/; not really sure how it differs), that "workon" is separate from "activate" which makes it easy to use on a virtualenv located anywhere.

Is it possible to expose similar functionality in this package? (despite the name)

Just as `virtualenvwrapper` enhances `virtualenv`, it seems like some of the virtualenv-only logic could be pulled into a separate package, although I'm sure this increases complexity.

Thank you for your thoughts.

**Comment by porterjamesj** [comment]
Hey!

Yeah this is a definite shortcoming. I originally wrote this to scratch a personal itch and at the time I used virtualenvwrapper for everything, so support for vanilla virtualenv is definitely lacking :)

That said there is rudimentary support, the relevant README section:



>If you have your virtualenvs spread around the filesystem rather than in one directory, just set venv-location to be a list of paths to each virtualenv. For example:

```
(setq venv-location '("/path/to/project1-env/"
                      "/path/to/ptoject2-env/"))
```

>Notice that the final directory of each path has a different name. The mode uses this fact to disambiguate virtualenvs from each other, so for now it is required.

The main difficulty in supporting vanilla virtualenv is figuring out where the virtualenv is actually located on the filesystem, which is why the explicit list is required.

Now that I'm thinking about it projectile does sort of solve this problem; using `projectile-project-root` sounds like a pretty sound idea. I'm envisioning that the api could be something like a function `venv-workon-projectile`, which, when called, looks for a virtualenv at `{projectile-project-root}/.venv`, the `.venv` bit being a configurable default. Would that work for your use case?

**Comment by porterjamesj** [comment]
I'm wondering if there's a way to abstract something more general that isn't so coupled to projectile, but it might not be worth it, I imagine something like the above would handle most use-cases.

**Comment by ryankask** [comment]
I think `venv-workon-projectile` covers my use case. Of course this is something that virtualenvwrapper doesn't handle but it seems like a useful addition and something missing in the emacs python/virtualenv world (http://stackoverflow.com/questions/21246218/how-can-i-make-emacs-jedi-use-project-specific-virtualenvs; also virtualenvwrapper does have some project functionality though I don't use it).

If you wanted to abstract it you could have something like`venv-workon-project` and `venv-project-root` which would be bound to  `projectile-project-root` if the function was found or you could leave it to the user to set that in his or her config.

Anyway, thanks for your feedback and discussion.

**Comment by stefano-m** [comment]
Hi @ryankask,

maybe PR #27 could solve your issue? You could add an [advice](https://www.gnu.org/software/emacs/manual/html_node/elisp/Advising-Functions.html) so that you can change `venv-location` based on `projectile-project-root` whenever you open a new project with projectile.

**Comment by ryankask** [comment]
Hi @stefano-m,

Thanks for letting me know about that PR.

It seems I've been able to accomplish most of what I want by just setting `python-shell-virtualenv-path` in a project's `.dir-locals.el`. It's very basic  but I've also been able to take advantage of [emacs-python-environment as well](https://github.com/tkf/emacs-python-environment).

**Comment by stefano-m** [comment]
Should this issue be closed now that PR #27 has been merged?

**Comment by porterjamesj** [comment]
@stefano-m I think I'll leave it open since I'd like to have some kind of more automagical projectile integration someday.

**Comment by ZzAntares** [comment]
Hi, I just wanted this feature too so here are my two cents, this is how I did it:

``` elisp
(setq venv-dirlookup-names '(".venv"))

(defun venv--set-projectile-workon ()
  "If a venv in the projetile root exists calls venv-workon it."
  (catch 'zz
    (dolist (path venv-dirlookup-names)
      (when (file-exists-p (concat (projectile-project-root) path))
        (venv-workon path)
        (throw 'zz path)))))

(setq projectile-switch-project-action
      '(lambda ()
         (venv--set-projectile-workon)
         (helm-projectile-find-file)))
```

With this every time I use `projectile-switch-project` the function `venv--set-projectile-workon` will be called and tries to find a `.venv` folder, and if it founds any, it will activate such env. Notice this solution recalls on `projectile-switch-project-action` value which a user can customise easily. Another way of triggering the function can be with hooks:

``` elisp
(add-hook 'python-mode-hook 'venv--set-projectile-workon)
```

However this will run on unneeded times, or we can use projectile hooks:

``` elisp
(add-hook 'projectile-find-file-hook 'venv--set-projectile-workon)
(add-hook 'projectile-find-dir-hook 'venv--set-projectile-workon)
```

But for me it doesn't work, I use `helm-projectile` and seems not to fire the hooks until I open a file for the second time.

Of course instead of hacking our `init.el` it will be easier if support for this came out of the box but for the time being that code does the trick, let me know what you guys think, I could prepare a PR for this if needed.

Thanks.

**Comment by porterjamesj** [comment]
@ZzAntares very cool, thank you for doing this! I would love to have this officially be part of virtualenvwrapper.el. I think the thing to do is to just include an implementation of `venv--set-projectile-workon`, and have a section in the README telling people to add it to their `projectile-switch-project-action` if they'd like to.

One minor nit if you do end up submitting a PR—it would be nice to have an implementation that doesn't use `throw`, maybe by using [dash's `-first`](https://github.com/magnars/dash.el#-first-pred-list) to find the first matching directory instead?

**Comment by ZzAntares** [comment]
Donzo!

Please review, I just changed the function name to be more meaningful and changed the code to use `-first` which is cleaner (I didn't know about dash 👍 ).

**Comment by porterjamesj** [comment]
(closing this since we now have "some kind of more automagical projectile integration")
