### ISSUE TITLE
PDB support

### ISSUE THREAD

**Issue by novakboskov** [porterjamesj/virtualenvwrapper.el#26]
When I run PDB with ```M-x pdb``` to debug something it uses my system wide Python installation and not one from virtualenv. Have you thought about PDB when you made this package? I don't know is it real issue or you just don't have PDB in mind.

**Comment by stefano-m** [comment]
virtualenv does not install PDB when a virtual environment is created, so niether virtualenvwrapper nor virtualenvwrapper.el can do something about it.

@porterjamesj, I have defined [some advice functions in my personal config](https://notabug.org/stefano-m/.emacs.d/src/master/site-lisp/virtualenvwrapper-extras.el#L39) that change the way pdb is called when a virtual env is activated so that `python -m pdb` is called. This should be enough to ensure that the correct python is used. If you think it's worth, I can submit a pull request to integrate the change.

**Comment by porterjamesj** [comment]
@novakboskov Hey, sorry I never got back to you on this, things have been pretty hectic. I'd never heard of `M-x pdb` before so no, I definitely didn't have it in mind. It's certainly in the spirit of this package that it should work though.

@stefano-m your code looks good, if you're willing to integrate and submit a PR that would be fantastic.

**Comment by stefano-m** [comment]
Should this be closed now that PR #28 is merged?

**Comment by porterjamesj** [comment]
:+1:
